[MI-2872]:Fixed issue #548 on github 'org lock for username'
Brightscout/mattermost-plugin-github pull request #23
Opened 2023-03-13 08:23 UTC by Kshitij-Katiyar

https://github.com/mattermost/mattermost-plugin-github/issues/548

2023-03-13 10:28 UTC, ayusht2810 commented on server/plugin/api.go
> +		allRepos = append(allRepos, repos...)
```suggestion
		}
		
		allRepos = append(allRepos, repos...)
```

2023-03-13 10:28 UTC, ayusht2810 commented on server/plugin/api.go
> +		opt.Page = resp.NextPage
```suggestion
		}
		
		opt.Page = resp.NextPage
```

2023-03-13 10:28 UTC, ayusht2810 commented on server/plugin/api.go
> +				if resp.StatusCode == 404 {
```suggestion
				if resp.StatusCode == http.StatusNotFound {
```

2023-03-13 10:59 UTC, raghavaggarwal2308 requested changes

2023-03-13 10:59 UTC, raghavaggarwal2308 commented on server/plugin/api.go
> +				c.Log.WithError(lErr).Warnf("Failed to list repositories by org")
```suggestion

				c.Log.WithError(lErr).Warnf("Failed to list repositories by organization")
```

2023-03-13 10:59 UTC, raghavaggarwal2308 commented on server/plugin/api.go
> +			repos, resp, lErr := githubClient.Repositories.ListByOrg(c.Ctx, org, &github.RepositoryListByOrgOptions{Sort: "full_name", ListOptions: opt})
Constant for `full_name`?

2023-03-13 10:59 UTC, raghavaggarwal2308 commented on server/plugin/api.go
```suggestion
```

2023-03-14 10:03 UTC, Kshitij-Katiyar commented on server/plugin/api.go
> +			repos, resp, lErr := githubClient.Repositories.ListByOrg(c.Ctx, org, &github.RepositoryListByOrgOptions{Sort: "full_name", ListOptions: opt})
copied from above

2023-03-14 10:27 UTC, raghavaggarwal2308 approved these changes

2023-03-15 11:34 UTC, avas27JTG commented on server/plugin/api.go
> +				}
I think `404` is shown even when a repo is not accessible but the org/repo name is valid, see if this also needs to be handled here

2023-03-16 10:46 UTC, Kshitij-Katiyar commented on server/plugin/api.go
> +				}
yeah, Abhishek, I tried with not accessible org as well but the error in both cases is the same and there is no defining difference for which we can differentiate between the 2 cases. As the error is also same there will be no difference for the user experience

2023-03-20 07:36 UTC, avas27JTG approved these changes

2023-03-20 07:38 UTC, merged