[MM-617]: converted the custom post to slack attachment for issue creation event on Github
Brightscout/mattermost-plugin-github pull request #37
Opened 2024-07-22 10:05 UTC by Kshitij-Katiyar

### Summary
- Added a slack attachment to the notification whenever a user creates a github issue with Comment, Edit and Close action buttons.
![Screenshot from 2024-07-22 15-35-18](https://github.com/user-attachments/assets/b63c0d0e-f49e-470c-831b-32fff9671e6f)

2024-07-29 07:22 UTC, raghavaggarwal2308 requested changes

2024-07-29 07:22 UTC, raghavaggarwal2308 commented on server/plugin/api.go
> +func (p *Plugin) handleOpenEditModal(c *UserContext, w http.ResponseWriter, r *http.Request) {
```suggestion
func (p *Plugin) handleOpenEditIssueModal(c *UserContext, w http.ResponseWriter, r *http.Request) {
```

2024-07-29 07:22 UTC, raghavaggarwal2308 commented on server/plugin/api.go
> +	apiRouter.HandleFunc("/open-edit-modal", p.checkAuth(p.attachUserContext(p.handleOpenEditModal), ResponseTypePlain)).Methods(http.MethodPost)
Do we need the wrapper functions here?

2024-07-29 07:22 UTC, raghavaggarwal2308 commented on server/plugin/api.go
> +		p.API.LogError("Error decoding PostActionIntegrationRequest params: ", err.Error())
```suggestion
		p.API.LogError("Error decoding PostActionIntegrationRequest params", "Error", err.Error())
```

2024-07-29 07:22 UTC, raghavaggarwal2308 commented on server/plugin/api.go
> +	repoName := postActionIntegrationRequest.Context["repo_name"]
create constants for these

2024-07-29 07:22 UTC, raghavaggarwal2308 commented on server/plugin/api.go
> +		"edit_modal",
Constant

2024-07-29 07:22 UTC, raghavaggarwal2308 commented on server/plugin/api.go
> +		p.API.LogWarn("failed to write PostActionIntegrationResponse", "Error", err.Error())
```suggestion
		p.API.LogWarn("Failed to write PostActionIntegrationResponse", "Error", err.Error())
```

2024-07-29 07:22 UTC, raghavaggarwal2308 commented on server/plugin/api.go
> +		p.API.LogError("Error decoding PostActionIntegrationRequest params: ", err.Error())
same

2024-07-29 07:22 UTC, raghavaggarwal2308 commented on server/plugin/api.go
> +
```suggestion
```

2024-07-29 07:22 UTC, raghavaggarwal2308 commented on server/plugin/webhook.go
> +		pluginURL := *p.client.Configuration.GetConfig().ServiceSettings.SiteURL + "/" + "plugins" + "/" + Manifest.Id
create a util for this if not present already

2024-07-29 07:22 UTC, raghavaggarwal2308 commented on server/plugin/webhook.go
> +									URL: fmt.Sprintf("%s/api/v1/open-comment-modal", pluginURL),
Constant for these paths

2024-07-29 07:22 UTC, raghavaggarwal2308 commented on server/plugin/webhook.go
> +										"channel_id":   sub.ChannelID,
This should be present in the postActionIntegration request. So, no need to pass in context

2024-07-29 07:22 UTC, raghavaggarwal2308 commented on webapp/src/components/modals/attach_comment_to_issue/attach_comment_to_issue.jsx
> +            post_id: this.props.messageData.postId,
```suggestion
            post_id: postId,
```

2024-07-29 07:22 UTC, raghavaggarwal2308 commented on webapp/src/components/modals/close_reopen_issue/index.tsx
> +        const currentStatus = messageData?.status === 'open' ? statusReason : 'reopened';
Why have we made this change?

2024-07-29 07:22 UTC, raghavaggarwal2308 commented on webapp/src/components/modals/close_reopen_issue/index.tsx
> +            status: messageData.status === 'open' ? 'Close' : 'Reopen',
same

2024-07-30 08:09 UTC, Kshitij-Katiyar commented on webapp/src/components/modals/close_reopen_issue/index.tsx
> +            status: messageData.status === 'open' ? 'Close' : 'Reopen',
discussed

2024-07-30 08:09 UTC, Kshitij-Katiyar commented on webapp/src/components/modals/close_reopen_issue/index.tsx
> +        const currentStatus = messageData?.status === 'open' ? statusReason : 'reopened';
discussed and added comment in code

2024-07-30 17:21 UTC, raghavaggarwal2308 requested changes
We should also remove the existing custom post file from webapp as that is no longer needed.

2024-07-30 17:21 UTC, raghavaggarwal2308 commented on server/plugin/api.go
> +	RepoName          string       = "repo_name"
Use a prefix for these constants. I think these are key names so `KeyRepoName`

2024-07-30 17:21 UTC, raghavaggarwal2308 commented on server/plugin/api.go
> +	CommentModalHeader string = "comment_modal"
```suggestion
	HeaderCommentModal string = "comment_modal"
```
Common part should be used as prefix in constant names

2024-07-30 17:21 UTC, raghavaggarwal2308 commented on server/plugin/api.go
> +	CommentModalHeader string = "comment_modal"
Also it should be `WebsocketEventOpenCommantModal` and the value should be `open_comment_modal`

2024-07-30 17:21 UTC, raghavaggarwal2308 commented on server/plugin/webhook.go
> +	OpenStatusModalPath    string = "/open-status-modal"
move these to api.go file

2024-07-30 17:21 UTC, raghavaggarwal2308 commented on server/plugin/webhook.go
> +	CloseIssueModalTitle   string = "Close"
No need to create constants for these as there being used once only

2024-07-30 17:21 UTC, raghavaggarwal2308 commented on server/plugin/webhook.go
> +		pluginURL := p.flowManager.pluginURL
We should the the value of URL from plugin config. Because the use case of flow manager is different.

2024-07-30 17:21 UTC, raghavaggarwal2308 commented on server/plugin/webhook.go
> +									URL: fmt.Sprintf("%s%s%s", pluginURL, BasePath, OpenEditIssueModalPath),
We can create a util function like "getPluginAPIPath" to return `pluginURL/api/v1/`

2024-07-30 17:21 UTC, raghavaggarwal2308 commented on webapp/src/components/modals/attach_comment_to_issue/attach_comment_to_issue.jsx
> +            post_id: this.props.messageData?.postId,
```suggestion
            post_id: postId,
```

2024-07-30 17:21 UTC, raghavaggarwal2308 commented on server/plugin/utils.go
>  	post.Props[titleForProps] = issue.Title
Do we still need these?

2024-07-30 17:21 UTC, raghavaggarwal2308 commented on server/plugin/utils.go
> +	}
This logic is very complex and confusing. Since there are just two fields I think its better to just set the fields to {} initially and update them according to our new data. Let me know your opinions on this

2024-07-30 17:21 UTC, raghavaggarwal2308 commented on server/plugin/template_test.go
Why have we remove so many testcases here?

2024-08-01 05:41 UTC, Kshitij-Katiyar commented on webapp/src/components/modals/attach_comment_to_issue/attach_comment_to_issue.jsx
> +            post_id: this.props.messageData?.postId,
postId is not accessable here

2024-08-01 05:43 UTC, Kshitij-Katiyar commented on server/plugin/template_test.go
Since the details of the new issue are now being rendered as posts and most of the templates for `newIssue` have been removed, the removed test cases were not valid.

2024-08-01 06:29 UTC, Kshitij-Katiyar commented on server/plugin/utils.go
>  	post.Props[titleForProps] = issue.Title
Yes, we are still using this part of code to update the content of the post about issue details

2024-08-01 06:35 UTC, raghavaggarwal2308 commented on server/plugin/utils.go
>  	post.Props[titleForProps] = issue.Title
I think this was used in the custom post which we are removing in this PR and it has no use in the slack attachment. Can you please reverify?

2024-08-01 09:59 UTC, raghavaggarwal2308 requested changes

2024-08-01 09:59 UTC, raghavaggarwal2308 commented on server/plugin/plugin.go
> +	return fmt.Sprintf("%s/plugins/github/api/v1", *p.client.Configuration.GetConfig().ServiceSettings.SiteURL)
Use plugin ID from manifest file

2024-08-01 10:06 UTC, raghavaggarwal2308 requested changes

2024-08-01 10:06 UTC, raghavaggarwal2308 commented on server/plugin/api.go
> +	apiRouter.HandleFunc("/open-status-modal", p.checkAuth(p.attachUserContext(p.handleOpenIssueStatusModal), ResponseTypePlain)).Methods(http.MethodPost)
Use constants for path, already created on line 74

2024-08-01 10:06 UTC, raghavaggarwal2308 commented on server/plugin/api.go
> +		p.API.LogError("Error decoding PostActionIntegrationRequest params", "Error", err.Error())
We should give some error to the user in case of error

2024-08-01 10:06 UTC, raghavaggarwal2308 commented on server/plugin/api.go
> +		p.API.LogError("Error decoding PostActionIntegrationRequest params", "Error", err.Error())
Maybe an ephemeral post

2024-08-01 10:06 UTC, raghavaggarwal2308 commented on server/plugin/utils.go
> +		p.writeAPIError(w, &APIErrorResponse{ID: "", Message: fmt.Sprintf("existing attachments format error: %v", err), StatusCode: http.StatusInternalServerError})
Do we need to log the error here?

2024-08-01 10:06 UTC, raghavaggarwal2308 commented on webapp/src/components/modals/close_reopen_issue/index.tsx
> +    const status = messageData.status === 'open' ? 'Close Issue' : 'Open Issue';
We can create a constant for this before hand as we are performing the same action twice

2024-08-01 10:06 UTC, raghavaggarwal2308 commented on server/plugin/template_test.go
Just curious, why are the templates removed?

2024-08-01 11:21 UTC, Kshitij-Katiyar commented on server/plugin/template_test.go
All the info rendered from templates are present in the slack attachment, so it was getting redundent.

2024-08-01 11:42 UTC, raghavaggarwal2308 requested changes

2024-08-01 11:42 UTC, raghavaggarwal2308 commented on server/plugin/api.go
> +	OpenIssueCommentModalPath string = "/open-comment-modal"
```suggestion
	PathOpenIssueCommentModal string = "/open-comment-modal"
```

2024-08-01 11:42 UTC, raghavaggarwal2308 commented on server/plugin/utils.go
> +		p.client.Log.Warn("Error occurred while getting attachments from props. PostID: %v. Error: %v", post.Id, err)
Fix the log syntax

2024-08-06 07:57 UTC, raghavaggarwal2308 approved these changes

2024-08-06 07:57 UTC, raghavaggarwal2308 commented on server/plugin/utils.go
> +		c.Log.WithError(err).Warnf("Error occurred while getting attachments from props. PostID: %v.", post.Id)
Whybare we not using p.clint.log ?

2024-08-06 09:45 UTC, merged