MM-794: returning proper JSON response from APIs
Brightscout/mattermost-plugin-github pull request #39
Opened 2024-08-30 11:05 UTC by Kshitij-Katiyar

#### Summary
returning proper JSON response from APIs

2024-09-02 11:25 UTC, raghavaggarwal2308 reviewed
Please test the PR for error responses of all the APIs also add logging wherever necessary

2024-09-22 13:49 UTC, raghavaggarwal2308 requested changes

2024-09-22 13:49 UTC, raghavaggarwal2308 commented on server/plugin/api.go
> +			p.writeAPIError(w, &APIErrorResponse{Message: "this plugin is not configured", StatusCode: http.StatusNotImplemented})
Why not adding log here?

2024-09-22 13:49 UTC, raghavaggarwal2308 commented on server/plugin/api.go
> +			p.writeAPIError(w, &APIErrorResponse{Message: "this plugin is not configured", StatusCode: http.StatusNotImplemented})
Also at other places

2024-09-23 11:01 UTC, Kshitij-Katiyar commented on server/plugin/api.go
> +			p.writeAPIError(w, &APIErrorResponse{Message: "this plugin is not configured", StatusCode: http.StatusNotImplemented})
Added

2024-09-26 12:06 UTC, raghavaggarwal2308 approved these changes

2024-09-26 12:06 UTC, raghavaggarwal2308 commented on server/plugin/api.go
> +		p.client.Log.Error("UserID not found.")
Add userID

2024-09-26 12:31 UTC, raghavaggarwal2308 commented on server/plugin/api.go
> +		p.client.Log.Error("UserID not found.")
Oh I see it is empty

2024-09-26 13:25 UTC, Kshitij-Katiyar commented
Created a PR on mattermost remote with all these changes hence closing this one

2024-09-26 13:25 UTC, closed without merging