[MM-468]: Include number of lines changed in RHS PR list
Brightscout/mattermost-plugin-github pull request #41
Opened 2024-09-03 11:26 UTC by Kshitij-Katiyar

### Summary
Include the number of lines changed in the RHS PR list

### Screenshot
#### Existing
![Screenshot from 2024-09-03 16-55-42](https://github.com/user-attachments/assets/825c90b8-3e96-47d0-8a90-d9fb240b645e)
![Screenshot from 2024-09-03 16-55-52](https://github.com/user-attachments/assets/7112e96a-c318-4703-b233-04a37759a901)
#### Updated
![Screenshot from 2024-09-03 16-50-28](https://github.com/user-attachments/assets/fca5cef3-0f09-405a-965b-567322b3f612)
![Screenshot from 2024-09-03 16-50-41](https://github.com/user-attachments/assets/5b722f7d-140d-4a93-b2dc-7b103570fb8a)

### How to test
- Connect your mattermost to GitHub
- Create a PR on GitHub with another account and add the GitHub account connected with mattermost as the reviewer
- Open the RHS PR list

2024-09-06 11:20 UTC, raghavaggarwal2308 requested changes

2024-09-06 11:20 UTC, raghavaggarwal2308 commented on server/plugin/graphql/lhs_request.go
> +	ChangedFiles *githubv4.Int `json:"changed_files,omitempty"`
```suggestion
	FilesChanged *githubv4.Int `json:"files_changed, omitempty"`
```

2024-09-06 11:20 UTC, raghavaggarwal2308 commented on server/plugin/graphql/lhs_request.go
> +	return newGithubPR(resp.Number, resp.Title, resp.Author.Login, resp.Repository.URL, resp.URL, resp.CreatedAt, resp.UpdatedAt, labels, resp.Milestone.Title, resp.Additions, resp.Deletions, resp.Chang
I don't think there is need for creating this function we can directly return the data from here. Please let me know if you have something else in mind.

2024-09-06 11:20 UTC, raghavaggarwal2308 commented on webapp/src/components/sidebar_right/github_items.tsx
> +                    {changedFiles != null && (
```suggestion
                    {changedFiles && (
```

2024-09-09 06:48 UTC, Kshitij-Katiyar commented on server/plugin/graphql/lhs_request.go
> +	ChangedFiles *githubv4.Int `json:"changed_files,omitempty"`
cant update the JSON, should we update the var name only?

2024-09-09 06:49 UTC, Kshitij-Katiyar commented on server/plugin/graphql/lhs_request.go
> +	return newGithubPR(resp.Number, resp.Title, resp.Author.Login, resp.Repository.URL, resp.URL, resp.CreatedAt, resp.UpdatedAt, labels, resp.Milestone.Title, resp.Additions, resp.Deletions, resp.Chang
the new function is used only once so yes we can directly return the data

2024-09-13 11:22 UTC, raghavaggarwal2308 commented on server/plugin/graphql/lhs_request.go
> +	ChangedFiles *githubv4.Int `json:"changed_files,omitempty"`
Why can't we change the json?

2024-09-17 04:14 UTC, Kshitij-Katiyar commented on server/plugin/graphql/lhs_request.go
> +	ChangedFiles *githubv4.Int `json:"changed_files,omitempty"`
@raghavaggarwal2308 API response is not getting serialized if we update the json

2024-09-19 14:21 UTC, raghavaggarwal2308 approved these changes

2024-09-23 05:24 UTC, Kshitij-Katiyar commented
Created a PR on mattermost remote with all these changes hence closed this one

2024-09-23 05:24 UTC, closed without merging